version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: erb-postgres
    restart: always
    environment:
      POSTGRES_USER: erb_User@i7oi
      POSTGRES_PASSWORD: erb_P@ssW0rdi7oi
      POSTGRES_DB: erb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erb-net

volumes:
  postgres_data:

networks:
  erb-net:
    driver: bridge